import { createApp } from "vue";
import { VueCookieNext } from "vue-cookie-next";
import App from "./App.vue";
import router from "./router";
import { store, key } from "./store";
import {
  create,
  NA,
  NAutoComplete,
  NButton,
  NButtonGroup,
  NCard,
  NCheckbox,
  NCollapseTransition,
  NConfigProvider,
  NEmpty,
  NForm,
  NFormItem,
  NGlobalStyle,
  NGrid,
  NGridItem,
  NH1,
  NH2,
  NH3,
  NH4,
  NIcon,
  NInput,
  NInputGroup,
  NLayout,
  NLayoutContent,
  NLayoutFooter,
  NLayoutHeader,
  NLayoutSider,
  NMenu,
  NPopconfirm,
  NPopselect,
  NResult,
  NScrollbar,
  NSpace,
  NTabPane,
  NTabs,
  NText,
  NTooltip
} from "naive-ui";

const naive = create({
  components: [
    NA,
    NAutoComplete,
    NButton,
    NButtonGroup,
    NCard,
    NCheckbox,
    NCollapseTransition,
    NConfigProvider,
    NEmpty,
    NForm,
    NFormItem,
    NGlobalStyle,
    NGrid,
    NGridItem,
    NH1,
    NH2,
    NH3,
    NH4,
    NIcon,
    NInput,
    NInputGroup,
    NLayout,
    NLayoutContent,
    NLayoutFooter,
    NLayoutHeader,
    NLayoutSider,
    NMenu,
    NPopconfirm,
    NPopselect,
    NResult,
    NScrollbar,
    NSpace,
    NTabPane,
    NTabs,
    NText,
    NTooltip
  ]
});

createApp(App).use(store, key).use(router).use(naive).use(VueCookieNext).mount("#app");
