version: "3.2"

services:
  redis_cache:
    image: "redis:alpine"
    container_name: taledynamic_redis_cache
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/dev-tools/redis/data:/var/lib/redis
      - $PWD/dev-tools/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres
    container_name: taledynamic_postgres
    volumes:
      - $PWD/dev-tools/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  